services:
  lint_api:
    image: lint_api:latest
    container_name: lint_api
    ports:
      - 3131
    networks:
      - caddy_net

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - caddy_net
volumes:
  caddy_data:
  caddy_config:

networks:
  caddy_net:
    name: caddy_net
