name: Docker Build and Deploy

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout Repository
            uses: actions/checkout@v4

        -   name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

        -   name: Copy .env file
            run: cp .env.example .env

        -   name: Build Docker Image
            run: docker build --build-arg ENV_FILE=.env -t brownei/lint-backend .

        -   name: Push Docker Image
            run: docker push brownei/lint-backend

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: Install SSH key
                uses: webfactory/ssh-agent@v0.9.0
                with:
                    ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

            -   name: Deploy to EC2
                run: |
                    scp -o StrictHostKeyChecking=no .env ec2-user@ec2-107-22-133-44.compute-1.amazonaws.com:/home/ec2-user/.env
                    ssh -o StrictHostKeyChecking=no ec2-user@ec2-107-22-133-44.compute-1.amazonaws.com << 'EOF'
                    if sudo docker ps -q --filter "status=running" | grep -q .; then
                        sudo docker stop $(sudo docker ps -q --filter "status=running")
                    fi
                    if sudo docker ps -a -q | grep -q .; then
                        sudo docker rm $(sudo docker ps -a -q)
                    fi
                    sudo docker pull brownei/lint-backend
                    sudo docker run --env-file /home/ec2-user/.env -d -p 3131:3131 brownei/lint-backend
                    sudo docker image prune -f
                    EOF
